---
- name: Install Docker and deploy Docker Compose application
  hosts: all
  become: yes
  vars:
    docker_compose_version: "v2.24.5"
    docker_compose_path: /usr/local/bin/docker-compose

  tasks:
    # Update apt package index
    - name: Update apt package index
      apt:
        update_cache: yes
        cache_valid_time: 3600

    # Install required system packages
    - name: Install required system packages
      apt:
        name:
          - apt-transport-https
          - ca-certificates
          - curl
          - gnupg-agent
          - software-properties-common
        state: present

    # Add Docker GPG key (alternative method that works reliably)
    - name: Add Docker GPG key
      ansible.builtin.get_url:
        url: https://download.docker.com/linux/ubuntu/gpg
        dest: /usr/share/keyrings/docker-archive-keyring.gpg
        mode: '0644'

    # Clean up any existing docker.list files to avoid conflicts
    - name: Remove existing Docker repository files
      ansible.builtin.file:
        path: /etc/apt/sources.list.d/docker.list
        state: absent

    # Add Docker repository (properly formatted)
    - name: Add Docker repository
      ansible.builtin.apt_repository:
        repo: "deb [arch=amd64 signed-by=/usr/share/keyrings/docker-archive-keyring.gpg] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable"
        filename: docker
        state: present
        update_cache: yes

    # Install Docker packages
    - name: Install Docker packages
      apt:
        name:
          - docker-ce
          - docker-ce-cli
          - containerd.io
        state: present
        update_cache: yes

    # Add user to docker group
    - name: Add user to docker group
      user:
        name: "{{ ansible_user }}"
        groups: docker
        append: yes

    # Download and install Docker Compose
    - name: Download Docker Compose
      get_url:
        url: "https://github.com/docker/compose/releases/download/{{ docker_compose_version }}/docker-compose-linux-x86_64"
        dest: "{{ docker_compose_path }}"
        mode: '0755'
        force: yes

    # Verify installations
    - name: Verify Docker installation
      command: docker --version
      register: docker_version
      changed_when: false

    - name: Verify Docker Compose installation
      command: docker-compose --version
      register: docker_compose_version
      changed_when: false

    - name: Show Docker version
      debug:
        msg: "{{ docker_version.stdout }}"

    - name: Show Docker Compose version
      debug:
        msg: "{{ docker_compose_version.stdout }}"

    # Create directory for docker-compose files
    - name: Create application directory
      file:
        path: /opt/myapp
        state: directory
        mode: '0755'

    # Copy your docker-compose.yml file
    - name: Copy docker-compose.yml
      copy:
        src: /path/to/your/docker-compose.yml  # Update this path
        dest: /opt/myapp/docker-compose.yml
        mode: '0644'

 
