#version: '3.8'

services:
  web:
    #build: . # Build the image from the Dockerfile in the current directory
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "5000:5000" # Map host port 5000 to container port 5000
    environment:
      # These environment variables are used by app.py to connect to the database
      DB_HOST: db # 'db' is the service name for the PostgreSQL container within the Docker network
      DB_NAME: mydatabase
      DB_USER: myuser
      DB_PASSWORD: mypassword
    depends_on:
      - db # Ensure the database container starts before the web container
    volumes:
      - ./app:/app # Mount the local app directory into the container for easier development/updates (optional for production)

  db:
    image: postgres:13 # Use an official PostgreSQL 13 image
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/postgresql/data # Persist database data to a named volume
    ports:
      - "5432:5432" # Expose DB port for debugging/admin tools (optional, remove for stricter security)

volumes:
  db_data: # Define the named volume for database persistence
